# ADR 004 spike example. See config/agents/opencode/flake.nix for shape notes.
{
  description = "pi coding agent image";

  # pi-coding-agent is only packaged on nixos-unstable (absent from 25.05/25.11).
  # The package exports a wrapped bin/pi (see pkgs/by-name/pi/pi-coding-agent).
  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

  outputs = { self, nixpkgs }:
    let
      system = "x86_64-linux";
      # nixpkgs config generated by agent-pod from `flake.*` settings (unfree /
      # insecure opt-ins); non-default keys only. See flake-config.nix.
      userFlakeConfig = import ./flake-config.nix;
      pkgs = import nixpkgs { inherit system; config = userFlakeConfig; };
      # Run pi inside its nix environment: put the nix nodejs (which also ships
      # npm/npx) on PATH before execing the real pi, so pi's startup
      # `npm install` of extensions resolves npm from the store closure instead
      # of needing an apt-installed node.
      pi = pkgs.writeShellScriptBin "pi" ''
        export PATH="${pkgs.nodejs}/bin:$PATH"
        exec ${pkgs.pi-coding-agent}/bin/pi "$@"
      '';
      # Stable /usr/local/bin symlink so the runner's thin layer can exec the
      # agent without knowing the nix store hash of the pi closure.
      links = pkgs.runCommand "pi-links" { } ''
        mkdir -p $out/usr/local/bin
        ln -s ${pi}/bin/pi $out/usr/local/bin/pi
      '';
      # FHS loader shim. Tools that download their own glibc runtimes at
      # use-time (uv, pnpm/corepack, rustup, deno, ...) exec them via the
      # standard dynamic linker path; nix binaries instead carry a patched
      # interpreter into the store. Symlinking the glibc loader at its standard
      # path lets those downloaded runtimes run. User-supplied flakes need the
      # same shim.
      fhs-libs = pkgs.runCommand "fhs-libs" { } ''
        mkdir -p $out/lib64
        ln -s ${pkgs.glibc}/lib/ld-linux-x86-64.so.2 $out/lib64/ld-linux-x86-64.so.2
      '';
      # Generated by agent-pod from `flake.extra_packages`; do not edit. The
      # flake (not a generated Dockerfile) is the source of truth for what is
      # installed in the image.
      extra = import ./extra-packages.nix { inherit pkgs; };
    in
    {
      packages.${system} = {
        # bin/pi; its store closure (incl. node runtime + ripgrep/fd wrapper deps) is the image.
        inherit pi;

        # The runtime image. The runner's thin layer sets the agent CLI as the
        # image ENTRYPOINT and tags the result as <image_tag>.
        image = pkgs.dockerTools.buildLayeredImage {
          name = "agent-pod/pi";
          tag = "spike";
          contents = [ pkgs.bash pkgs.git pkgs.coreutils pkgs.cacert pi links fhs-libs ] ++ extra;
          config = {
            Cmd = [ "${pi}/bin/pi" ];
            WorkingDir = "/sandbox";
            # HOME=/root keeps pi's agent dir at /root/.pi/agent, matching the
            # runner's baked settings.json; SSL_CERT_FILE points npm/curl/git at
            # the CA bundle pkgs.cacert installs (dockerTools images have no
            # system CA store otherwise).
            Env = [
              "HOME=/root"
              "SSL_CERT_FILE=/etc/ssl/certs/ca-bundle.crt"
            ];
            Entrypoint = [ "${pi}/bin/pi" ];
          };
        };
      };

      devShells.${system}.default = pkgs.mkShell {
        packages = [ pi pkgs.git ];
        shellHook = ''
          echo "[pi] pi on PATH; project deps live in the working dir (mutable), not /nix/store"
        '';
      };
    };
}
