# ADR 004 flake example. Notes below only cover flake-shape gotchas.

# opencode is packaged on nixos-unstable (and nixos-25.05, which shipped an
# ancient 0.3.x opencode without working provider support). Pin unstable
# to the same rev as the pi flake so both agents share one locked nixpkgs and
# opencode tracks current models.dev provider data.
{
  description = "opencode agent image (spike)";

  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

  outputs = { self, nixpkgs }:
    let
      system = "x86_64-linux";
      # nixpkgs config generated by agent-pod from `flake.*` settings (unfree /
      # insecure opt-ins); non-default keys only. See flake-config.nix.
      userFlakeConfig = import ./flake-config.nix;
      pkgs = import nixpkgs { inherit system; config = userFlakeConfig; };
      opencode = pkgs.opencode;
      # Stable /usr/local/bin symlink so the runner's thin layer can exec the
      # agent without knowing the nix store hash of the opencode closure.
      links = pkgs.runCommand "opencode-links" { } ''
        mkdir -p $out/usr/local/bin
        ln -s ${opencode}/bin/opencode $out/usr/local/bin/opencode
      '';
      # FHS loader shim. Tools that download their own glibc runtimes at
      # use-time (uv, pnpm/corepack, rustup, deno, ...) exec them via the
      # standard dynamic linker path; nix binaries instead carry a patched
      # interpreter into the store. Symlinking the glibc loader at its standard
      # path lets those downloaded runtimes run. User-supplied flakes need the
      # same shim.
      fhs-libs = pkgs.runCommand "fhs-libs" { } ''
        mkdir -p $out/lib64
        ln -s ${pkgs.glibc}/lib/ld-linux-x86-64.so.2 $out/lib64/ld-linux-x86-64.so.2
      '';
      # Generated by agent-pod from `flake.extra_packages`; do not edit. The
      # flake (not a generated Dockerfile) is the source of truth for what is
      # installed in the image.
      extra = import ./extra-packages.nix { inherit pkgs; };
    in
    {
      packages.${system} = {
        # The agent drv: its store closure is the image. Exported so
        # `nix build .#opencode` works, incl. from the nix-in-container build.
        inherit opencode;

        # The runtime image. The runner's thin layer sets the agent CLI as the
        # image ENTRYPOINT and tags the result as <image_tag>.
        image = pkgs.dockerTools.buildLayeredImage {
          name = "agent-pod/opencode";
          tag = "spike";
          contents = [ pkgs.bash pkgs.git pkgs.coreutils pkgs.cacert opencode links fhs-libs ] ++ extra;
          config = {
            Cmd = [ "${opencode}/bin/opencode" ];
            WorkingDir = "/sandbox";
            Env = [
              "HOME=/root"
              "SSL_CERT_FILE=/etc/ssl/certs/ca-bundle.crt"
            ];
            Entrypoint = [ "${opencode}/bin/opencode" ];
          };
        };
      };

      # `nix develop` authoring check: project deps go in ./venv etc. (mutable),
      # not the store.
      devShells.${system}.default = pkgs.mkShell {
        packages = [ opencode pkgs.git ];
        shellHook = ''
          echo "[spike] opencode on PATH; project deps live in the working dir (mutable), not /nix/store"
        '';
      };
    };
}
