# Claude Code is packaged on nixos-unstable as `claude-code` (Anthropic's
# proprietary binary, meta.license = unfree), so this flake's own nixpkgs
# instance enables allowUnfree to build it. Pin unstable to the same rev as the
# pi/opencode flakes so all agents share one locked nixpkgs.
{
  description = "claude code agent image";

  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

  outputs = { self, nixpkgs }:
    let
      system = "x86_64-linux";
      # nixpkgs config generated by agent-pod from `flake.*` settings (unfree /
      # insecure opt-ins); non-default keys only. claude-code itself is unfree,
      # so the agent's own allowUnfree always holds and the generated config can
      # only add keys (defaults are never emitted).
      userFlakeConfig = import ./flake-config.nix;
      pkgs = import nixpkgs {
        inherit system;
        config = { allowUnfree = true; } // userFlakeConfig;
      };
      claude = pkgs.claude-code;
      # Stable /usr/local/bin symlink so the runner's thin layer can exec the
      # agent without knowing the nix store hash of the claude closure.
      links = pkgs.runCommand "claude-links" { } ''
        mkdir -p $out/usr/local/bin
        ln -s ${claude}/bin/claude $out/usr/local/bin/claude
      '';
      # FHS loader shim. Tools that download their own glibc runtimes at
      # use-time (uv, pnpm/corepack, rustup, deno, ...) exec them via the
      # standard dynamic linker path; nix binaries instead carry a patched
      # interpreter into the store. Symlinking the glibc loader at its standard
      # path lets those downloaded runtimes run. User-supplied flakes need the
      # same shim.
      fhs-libs = pkgs.runCommand "fhs-libs" { } ''
        mkdir -p $out/lib64
        ln -s ${pkgs.glibc}/lib/ld-linux-x86-64.so.2 $out/lib64/ld-linux-x86-64.so.2
      '';
      # Generated by agent-pod from `flake.extra_packages`; do not edit. The
      # flake (not a generated Dockerfile) is the source of truth for what is
      # installed in the image.
      extra = import ./extra-packages.nix { inherit pkgs; };
    in
    {
      packages.${system} = {
        # The agent drv: bin/claude; its store closure (incl. the bun runtime,
        # bubblewrap/socat sandbox deps, ripgrep, procps) is the image.
        inherit claude;

        # The runtime image. The runner's thin layer sets the agent CLI as the
        # image ENTRYPOINT and tags the result as <image_tag>.
        image = pkgs.dockerTools.buildLayeredImage {
          name = "agent-pod/claude";
          tag = "spike";
          contents = [ pkgs.bash pkgs.git pkgs.coreutils pkgs.cacert claude links fhs-libs ] ++ extra;
          config = {
            Cmd = [ "${claude}/bin/claude" ];
            WorkingDir = "/sandbox";
            Env = [
              "HOME=/root"
              "SSL_CERT_FILE=/etc/ssl/certs/ca-bundle.crt"
            ];
            Entrypoint = [ "${claude}/bin/claude" ];
          };
        };
      };

      # `nix develop` authoring check: project deps go in ./venv etc. (mutable),
      # not the store.
      devShells.${system}.default = pkgs.mkShell {
        packages = [ claude pkgs.git ];
        shellHook = ''
          echo "[claude] claude on PATH; project deps live in the working dir (mutable), not /nix/store"
        '';
      };
    };
}
