# Generated by agent-pod; do not edit.
let
  flake = builtins.getFlake "/src";
  system = "x86_64-linux";
  pkgs = import flake.inputs.nixpkgs {
    inherit system;
    # Force-allow so metadata can be inspected without build-time throws.
    config = { allowUnfree = true; allowInsecure = true; };
  };
  lib = pkgs.lib;
  names = [ @NAMES@ ];
  classify = name:
    if ! builtins.hasAttr name pkgs then
      { inherit name; status = "unknown"; }
    else
      let pkg = builtins.getAttr name pkgs; in
      {
        inherit name;
        status =
          if (pkg.meta.knownVulnerabilities or []) != [] then "insecure"
          else if lib.any (l: !(l.free or true))
                   (lib.filter builtins.isAttrs (lib.toList (pkg.meta.license or [])))
               then "unfree"
          else "ok";
      };
in
builtins.toJSON (map classify names)
