"""Interactive generation of user config files (`ap init`).

The wizard asks where to write the config, then walks through a short fixed
set of questions (default agent, context files, and extra Nix packages), each
answered explicitly so the generated config is a faithful record of the user's
choices. Every answer is validated against the
``UserConfig`` Pydantic model and re-prompted until it is valid, and each is
written to the file. The file is written to either the
project (``.agent-pod.yaml``) or global
(``~/.config/container-agents/.agent-pod.yaml``) level. ``ensure_user_config``
wires this into ``ap run`` so a first-time user is walked through creating a
config when none exists on any level.
"""

import sys
from pathlib import Path
from typing import Any, get_args, get_origin

import yaml
from pydantic import BaseModel, ValidationError

from agent_pod.config.loader import (
    get_all_agent_names,
    get_global_config_path,
    get_project_config_path,
    user_config_paths,
)
from agent_pod.types import UserConfig

# Header comment written above the generated YAML keys.
CONFIG_HEADER = (
    "# agent-pod user configuration (generated by `ap init`).\n"
    "# All keys are optional; unset values fall back to the bundled agent config\n"
    "# and CLI defaults. See agent-pod.example.yaml for the full list of options.\n"
)


def _ask(prompt: str, default: str | None = None, choices: list[str] | None = None) -> str:
    """Ask one question; an empty answer returns `default` (or '' if none).

    Re-prompts until the answer is one of `choices` when provided. Raises
    EOFError (Ctrl-D) or OSError (unreadable stdin) so the caller can cancel
    the wizard instead of looping forever.
    """
    suffix = f" [{default}]" if default else ""
    while True:
        raw = input(f"{prompt}{suffix}: ").strip()
        if not raw and default is not None:
            return default
        if not raw or choices is None or raw in choices:
            return raw
        print(f"Please choose one of: {', '.join(choices)}", file=sys.stderr)


def _choose_target(target: str | None) -> Path:
    """Resolve where to write the config: explicit `target` or ask the user."""
    if target == "global":
        return get_global_config_path()
    if target == "project":
        return get_project_config_path()
    answer = _ask(
        "Where should I write the config?",
        default="project",
        choices=["project", "global"],
    )
    return get_global_config_path() if answer == "global" else get_project_config_path()


def _strip_optional(annotation: Any) -> Any:
    """Unwrap ``Optional[T]`` / ``T | None`` to the non-None member."""
    args = get_args(annotation)
    non_none = [a for a in args if a is not type(None)]
    if non_none and len(args) > 1:
        return non_none[0]
    return annotation


def _field_kind(annotation: Any) -> str:
    """Classify a field annotation as ``str``, ``bool``, ``list``, ``dict``, or ``model``."""
    annotation = _strip_optional(annotation)
    origin = get_origin(annotation)
    if annotation is bool:
        return "bool"
    if origin is list:
        return "list"
    if origin is dict:
        return "dict"
    if isinstance(annotation, type) and issubclass(annotation, BaseModel):
        return "model"
    return "str"


def _parse(kind: str, raw: str) -> Any:
    """Parse free-text input into the Python value for a field of `kind`.

    Raises:
        ValueError: If `raw` cannot be parsed for the kind (e.g. bad bool/dict).
    """
    if kind == "bool":
        lowered = raw.strip().lower()
        if lowered in ("true", "yes", "y", "1"):
            return True
        if lowered in ("false", "no", "n", "0"):
            return False
        raise ValueError("expected true or false")
    if kind == "list":
        return [part.strip() for part in raw.split(",") if part.strip()]
    if kind == "dict":
        result: dict[str, str] = {}
        for part in raw.split():
            if "=" not in part:
                raise ValueError(f"expected KEY=VALUE pairs, got {part!r}")
            key, value = part.split("=", 1)
            result[key.strip()] = value.strip()
        return result
    return raw


def _validate_field(model_cls: type[BaseModel], name: str, value: Any) -> str | None:
    """Validate `value` against the model field `name`; return an error or None.

    The whole (optional) model is validated with only this one key set, so the
    answer is checked with the same Pydantic rules that loading the file uses.
    """
    try:
        model_cls.model_validate({name: value})
        return None
    except ValidationError as exc:
        return "; ".join(
            f"{'.'.join(str(part) for part in err['loc'])}: {err['msg']}" for err in exc.errors()
        )


def _kind_hint(kind: str) -> str:
    """A short usage hint appended to the prompt for a field kind."""
    if kind == "bool":
        return "(true/false)"
    if kind == "list":
        return "(comma-separated)"
    if kind == "dict":
        return "(KEY=VALUE, space-separated)"
    if kind == "model":
        return "(nested options)"
    return ""


def _ask_value(
    name: str,
    prompt: str,
    *,
    choices: list[str] | None = None,
    default: str | None = None,
    required: bool = False,
) -> Any:
    """Ask one question; parse + validate the answer against the UserConfig model.

    The field's type is read from the ``UserConfig`` model, so the answer is
    parsed and validated with the same rules that loading the file uses. An
    empty answer returns the `default` (or None when there is no default);
    with `required=True` an empty answer re-prompts instead.
    """
    kind = _field_kind(UserConfig.model_fields[name].annotation)
    hint = _kind_hint(kind)
    if hint:
        prompt = f"{prompt} {hint}"
    while True:
        raw = _ask(prompt, default=default, choices=choices if kind == "str" else None)
        if not raw:
            if required:
                print(f"Please provide a value for {name}.", file=sys.stderr)
                continue
            return None
        try:
            value = _parse(kind, raw)
        except ValueError as exc:
            print(f"Invalid value for {name}: {exc}", file=sys.stderr)
            continue
        error = _validate_field(UserConfig, name, value)
        if error:
            print(f"Invalid value for {name}: {error}", file=sys.stderr)
            continue
        return value


def _gather_answers(agent_hint: str | None) -> dict:
    """Ask the fixed questions (all answered explicitly) and return them.

    Only a small, opinionated subset of the ``UserConfig`` fields is asked:
    the default agent, context files, and extra Nix packages. Every question
    is answered explicitly and its value is always written to the file, so
    the generated config is a faithful record of the user's choices.
    ``extra_packages`` is pre-filled with ``git, bash`` which the user can
    accept, extend, or change. The pi settings file is owned by the agent
    config, so it is never prompted for.
    """
    agents = get_all_agent_names()
    default_agent = agent_hint if agent_hint in agents else None

    data: dict = {}
    agent = _ask_value(
        "agent",
        "Default agent for `ap run`?",
        choices=agents,
        default=default_agent,
        required=default_agent is None,
    )
    data["agent"] = agent

    context_files = _ask_value(
        "context_files",
        "Mount context files (HOST_PATH[:NAME], comma-separated)?",
    )
    data["context_files"] = context_files or []

    extra_packages = _ask_value(
        "extra_packages",
        "Extra Nix packages to add (comma-separated)?",
        default="git, bash",
    )
    data["extra_packages"] = extra_packages or []

    return data


def write_config(path: Path, data: dict) -> Path:
    """Write `data` as a user config file at `path`, creating parent dirs."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(CONFIG_HEADER + yaml.safe_dump(data, sort_keys=False))
    return path


def run_init(
    agent_hint: str | None = None, target: str | None = None, force: bool = False
) -> Path | None:
    """Run the interactive wizard and write a config file.

    Args:
        agent_hint: Agent to pre-select as the default (from the CLI, if any).
        target: Write to ``"project"`` or ``"global"`` without asking, or ask
            when None.
        force: Overwrite the target config if it already exists instead of
            refusing.

    Returns:
        The path written, or None if nothing was written (the target already
        exists and ``force`` is False).
    """
    try:
        path = _choose_target(target)
    except (EOFError, OSError):
        # Ctrl-D (or unreadable stdin) cancels the wizard; write nothing.
        print("Cancelled; no config written.", file=sys.stderr)
        return None
    if path.exists() and not force:
        print(
            f"A config file already exists at {path}; not overwriting.\n"
            "Re-run with --force to overwrite it.",
            file=sys.stderr,
        )
        return None

    try:
        data = _gather_answers(agent_hint)
    except (EOFError, OSError):
        # Ctrl-D (or unreadable stdin) cancels the wizard; write nothing.
        print("Cancelled; no config written.", file=sys.stderr)
        return None
    return write_config(path, data)


def ensure_user_config(agent_hint: str | None = None) -> Path | None:
    """Generate a config on first use: called by `ap run` when none exists.

    If a user config exists on any level (global or project) this is a no-op.
    Interactive terminals get the full wizard; in non-interactive contexts
    (CI, pipes) a pointer to `ap init` is printed instead of silently writing
    a file.

    Returns:
        The path written by the wizard, or None if nothing was created.
    """
    if user_config_paths():
        return None
    if not sys.stdin.isatty():
        print(
            "No agent-pod config found (global or project); running "
            "non-interactively, so skipping config generation. "
            "Run `ap init` to create one.",
            file=sys.stderr,
        )
        return None
    return run_init(agent_hint=agent_hint)
